name: Build and Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.NEXTWP_TOKEN }}
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Push the Docker image to the GitHub Registry
        run: |
          docker push $DOCKER_IMAGE
          echo "::set-output name=image::${DOCKER_IMAGE}"
        env:
          DOCKER_PASSWORD: ${{ secrets.NEXTWP_TOKEN }}

      - name: Save Docker image URL as an output
        id: output-docker-image
        run: echo "::set-output name=image::${DOCKER_IMAGE}"

      - name: Upload a deployment artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ${{ steps.output-docker-image.outputs.image }}
